/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.guioas.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.xtext.example.guioas.ide.contentassist.antlr.internal.InternalGuiOasParser;
import org.xtext.example.guioas.services.GuiOasGrammarAccess;

public class GuiOasParser extends AbstractContentAssistParser {

	@Inject
	private GuiOasGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalGuiOasParser createParser() {
		InternalGuiOasParser result = new InternalGuiOasParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEntidadAccess().getGroup(), "rule__Entidad__Group__0");
					put(grammarAccess.getCampoAccess().getGroup(), "rule__Campo__Group__0");
					put(grammarAccess.getValidadorAccess().getGroup(), "rule__Validador__Group__0");
					put(grammarAccess.getEntidadAccess().getNombreAssignment_1(), "rule__Entidad__NombreAssignment_1");
					put(grammarAccess.getEntidadAccess().getCamposAssignment_4(), "rule__Entidad__CamposAssignment_4");
					put(grammarAccess.getEntidadAccess().getEntidadesAssignment_8(), "rule__Entidad__EntidadesAssignment_8");
					put(grammarAccess.getCampoAccess().getNameAssignment_1(), "rule__Campo__NameAssignment_1");
					put(grammarAccess.getCampoAccess().getNombreAssignment_2(), "rule__Campo__NombreAssignment_2");
					put(grammarAccess.getCampoAccess().getTipoAssignment_3(), "rule__Campo__TipoAssignment_3");
					put(grammarAccess.getCampoAccess().getLongitudAssignment_4(), "rule__Campo__LongitudAssignment_4");
					put(grammarAccess.getValidadorAccess().getNameAssignment_1(), "rule__Validador__NameAssignment_1");
					put(grammarAccess.getValidadorAccess().getNombreAssignment_2(), "rule__Validador__NombreAssignment_2");
					put(grammarAccess.getValidadorAccess().getLocacionAssignment_3(), "rule__Validador__LocacionAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalGuiOasParser typedParser = (InternalGuiOasParser) parser;
			typedParser.entryRuleEntidad();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GuiOasGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GuiOasGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
