/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.guioas.guiOas.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.guioas.guiOas.GuiOasPackage;
import org.xtext.example.guioas.guiOas.Validador;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Validador</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.guioas.guiOas.impl.ValidadorImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.guioas.guiOas.impl.ValidadorImpl#getNombre <em>Nombre</em>}</li>
 *   <li>{@link org.xtext.example.guioas.guiOas.impl.ValidadorImpl#getLocacion <em>Locacion</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ValidadorImpl extends MinimalEObjectImpl.Container implements Validador
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getNombre() <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre()
   * @generated
   * @ordered
   */
  protected static final String NOMBRE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNombre() <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre()
   * @generated
   * @ordered
   */
  protected String nombre = NOMBRE_EDEFAULT;

  /**
   * The default value of the '{@link #getLocacion() <em>Locacion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocacion()
   * @generated
   * @ordered
   */
  protected static final String LOCACION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLocacion() <em>Locacion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocacion()
   * @generated
   * @ordered
   */
  protected String locacion = LOCACION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ValidadorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GuiOasPackage.Literals.VALIDADOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GuiOasPackage.VALIDADOR__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNombre()
  {
    return nombre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNombre(String newNombre)
  {
    String oldNombre = nombre;
    nombre = newNombre;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GuiOasPackage.VALIDADOR__NOMBRE, oldNombre, nombre));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLocacion()
  {
    return locacion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLocacion(String newLocacion)
  {
    String oldLocacion = locacion;
    locacion = newLocacion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GuiOasPackage.VALIDADOR__LOCACION, oldLocacion, locacion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GuiOasPackage.VALIDADOR__NAME:
        return getName();
      case GuiOasPackage.VALIDADOR__NOMBRE:
        return getNombre();
      case GuiOasPackage.VALIDADOR__LOCACION:
        return getLocacion();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GuiOasPackage.VALIDADOR__NAME:
        setName((String)newValue);
        return;
      case GuiOasPackage.VALIDADOR__NOMBRE:
        setNombre((String)newValue);
        return;
      case GuiOasPackage.VALIDADOR__LOCACION:
        setLocacion((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GuiOasPackage.VALIDADOR__NAME:
        setName(NAME_EDEFAULT);
        return;
      case GuiOasPackage.VALIDADOR__NOMBRE:
        setNombre(NOMBRE_EDEFAULT);
        return;
      case GuiOasPackage.VALIDADOR__LOCACION:
        setLocacion(LOCACION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GuiOasPackage.VALIDADOR__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case GuiOasPackage.VALIDADOR__NOMBRE:
        return NOMBRE_EDEFAULT == null ? nombre != null : !NOMBRE_EDEFAULT.equals(nombre);
      case GuiOasPackage.VALIDADOR__LOCACION:
        return LOCACION_EDEFAULT == null ? locacion != null : !LOCACION_EDEFAULT.equals(locacion);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", nombre: ");
    result.append(nombre);
    result.append(", locacion: ");
    result.append(locacion);
    result.append(')');
    return result.toString();
  }

} //ValidadorImpl
