/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.guioas.guiOas;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Campo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.guioas.guiOas.Campo#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.guioas.guiOas.Campo#getNombre <em>Nombre</em>}</li>
 *   <li>{@link org.xtext.example.guioas.guiOas.Campo#getTipo <em>Tipo</em>}</li>
 *   <li>{@link org.xtext.example.guioas.guiOas.Campo#getLongitud <em>Longitud</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.guioas.guiOas.GuiOasPackage#getCampo()
 * @model
 * @generated
 */
public interface Campo extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.guioas.guiOas.GuiOasPackage#getCampo_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.guioas.guiOas.Campo#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nombre</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre</em>' attribute.
   * @see #setNombre(String)
   * @see org.xtext.example.guioas.guiOas.GuiOasPackage#getCampo_Nombre()
   * @model
   * @generated
   */
  String getNombre();

  /**
   * Sets the value of the '{@link org.xtext.example.guioas.guiOas.Campo#getNombre <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre</em>' attribute.
   * @see #getNombre()
   * @generated
   */
  void setNombre(String value);

  /**
   * Returns the value of the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tipo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' attribute.
   * @see #setTipo(String)
   * @see org.xtext.example.guioas.guiOas.GuiOasPackage#getCampo_Tipo()
   * @model
   * @generated
   */
  String getTipo();

  /**
   * Sets the value of the '{@link org.xtext.example.guioas.guiOas.Campo#getTipo <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' attribute.
   * @see #getTipo()
   * @generated
   */
  void setTipo(String value);

  /**
   * Returns the value of the '<em><b>Longitud</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Longitud</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Longitud</em>' attribute.
   * @see #setLongitud(int)
   * @see org.xtext.example.guioas.guiOas.GuiOasPackage#getCampo_Longitud()
   * @model
   * @generated
   */
  int getLongitud();

  /**
   * Sets the value of the '{@link org.xtext.example.guioas.guiOas.Campo#getLongitud <em>Longitud</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Longitud</em>' attribute.
   * @see #getLongitud()
   * @generated
   */
  void setLongitud(int value);

} // Campo
