/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.guioas.guiOas;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.guioas.guiOas.GuiOasPackage
 * @generated
 */
public interface GuiOasFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GuiOasFactory eINSTANCE = org.xtext.example.guioas.guiOas.impl.GuiOasFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Entidad</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entidad</em>'.
   * @generated
   */
  Entidad createEntidad();

  /**
   * Returns a new object of class '<em>Campo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Campo</em>'.
   * @generated
   */
  Campo createCampo();

  /**
   * Returns a new object of class '<em>Validador</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Validador</em>'.
   * @generated
   */
  Validador createValidador();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  GuiOasPackage getGuiOasPackage();

} //GuiOasFactory
