/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.guioas.guiOas;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.guioas.guiOas.GuiOasFactory
 * @model kind="package"
 * @generated
 */
public interface GuiOasPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "guiOas";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/guioas/GuiOas";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "guiOas";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GuiOasPackage eINSTANCE = org.xtext.example.guioas.guiOas.impl.GuiOasPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.guioas.guiOas.impl.EntidadImpl <em>Entidad</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.guioas.guiOas.impl.EntidadImpl
   * @see org.xtext.example.guioas.guiOas.impl.GuiOasPackageImpl#getEntidad()
   * @generated
   */
  int ENTIDAD = 0;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD__NOMBRE = 0;

  /**
   * The feature id for the '<em><b>Campos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD__CAMPOS = 1;

  /**
   * The feature id for the '<em><b>Entidades</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD__ENTIDADES = 2;

  /**
   * The number of structural features of the '<em>Entidad</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.guioas.guiOas.impl.CampoImpl <em>Campo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.guioas.guiOas.impl.CampoImpl
   * @see org.xtext.example.guioas.guiOas.impl.GuiOasPackageImpl#getCampo()
   * @generated
   */
  int CAMPO = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMPO__NAME = 0;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMPO__NOMBRE = 1;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMPO__TIPO = 2;

  /**
   * The feature id for the '<em><b>Longitud</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMPO__LONGITUD = 3;

  /**
   * The number of structural features of the '<em>Campo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMPO_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.guioas.guiOas.impl.ValidadorImpl <em>Validador</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.guioas.guiOas.impl.ValidadorImpl
   * @see org.xtext.example.guioas.guiOas.impl.GuiOasPackageImpl#getValidador()
   * @generated
   */
  int VALIDADOR = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDADOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDADOR__NOMBRE = 1;

  /**
   * The feature id for the '<em><b>Locacion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDADOR__LOCACION = 2;

  /**
   * The number of structural features of the '<em>Validador</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDADOR_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.example.guioas.guiOas.Entidad <em>Entidad</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entidad</em>'.
   * @see org.xtext.example.guioas.guiOas.Entidad
   * @generated
   */
  EClass getEntidad();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.guioas.guiOas.Entidad#getNombre <em>Nombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nombre</em>'.
   * @see org.xtext.example.guioas.guiOas.Entidad#getNombre()
   * @see #getEntidad()
   * @generated
   */
  EAttribute getEntidad_Nombre();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.guioas.guiOas.Entidad#getCampos <em>Campos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Campos</em>'.
   * @see org.xtext.example.guioas.guiOas.Entidad#getCampos()
   * @see #getEntidad()
   * @generated
   */
  EReference getEntidad_Campos();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.guioas.guiOas.Entidad#getEntidades <em>Entidades</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entidades</em>'.
   * @see org.xtext.example.guioas.guiOas.Entidad#getEntidades()
   * @see #getEntidad()
   * @generated
   */
  EReference getEntidad_Entidades();

  /**
   * Returns the meta object for class '{@link org.xtext.example.guioas.guiOas.Campo <em>Campo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Campo</em>'.
   * @see org.xtext.example.guioas.guiOas.Campo
   * @generated
   */
  EClass getCampo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.guioas.guiOas.Campo#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.guioas.guiOas.Campo#getName()
   * @see #getCampo()
   * @generated
   */
  EAttribute getCampo_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.guioas.guiOas.Campo#getNombre <em>Nombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nombre</em>'.
   * @see org.xtext.example.guioas.guiOas.Campo#getNombre()
   * @see #getCampo()
   * @generated
   */
  EAttribute getCampo_Nombre();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.guioas.guiOas.Campo#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see org.xtext.example.guioas.guiOas.Campo#getTipo()
   * @see #getCampo()
   * @generated
   */
  EAttribute getCampo_Tipo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.guioas.guiOas.Campo#getLongitud <em>Longitud</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Longitud</em>'.
   * @see org.xtext.example.guioas.guiOas.Campo#getLongitud()
   * @see #getCampo()
   * @generated
   */
  EAttribute getCampo_Longitud();

  /**
   * Returns the meta object for class '{@link org.xtext.example.guioas.guiOas.Validador <em>Validador</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Validador</em>'.
   * @see org.xtext.example.guioas.guiOas.Validador
   * @generated
   */
  EClass getValidador();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.guioas.guiOas.Validador#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.guioas.guiOas.Validador#getName()
   * @see #getValidador()
   * @generated
   */
  EAttribute getValidador_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.guioas.guiOas.Validador#getNombre <em>Nombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nombre</em>'.
   * @see org.xtext.example.guioas.guiOas.Validador#getNombre()
   * @see #getValidador()
   * @generated
   */
  EAttribute getValidador_Nombre();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.guioas.guiOas.Validador#getLocacion <em>Locacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Locacion</em>'.
   * @see org.xtext.example.guioas.guiOas.Validador#getLocacion()
   * @see #getValidador()
   * @generated
   */
  EAttribute getValidador_Locacion();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GuiOasFactory getGuiOasFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.guioas.guiOas.impl.EntidadImpl <em>Entidad</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.guioas.guiOas.impl.EntidadImpl
     * @see org.xtext.example.guioas.guiOas.impl.GuiOasPackageImpl#getEntidad()
     * @generated
     */
    EClass ENTIDAD = eINSTANCE.getEntidad();

    /**
     * The meta object literal for the '<em><b>Nombre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTIDAD__NOMBRE = eINSTANCE.getEntidad_Nombre();

    /**
     * The meta object literal for the '<em><b>Campos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTIDAD__CAMPOS = eINSTANCE.getEntidad_Campos();

    /**
     * The meta object literal for the '<em><b>Entidades</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTIDAD__ENTIDADES = eINSTANCE.getEntidad_Entidades();

    /**
     * The meta object literal for the '{@link org.xtext.example.guioas.guiOas.impl.CampoImpl <em>Campo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.guioas.guiOas.impl.CampoImpl
     * @see org.xtext.example.guioas.guiOas.impl.GuiOasPackageImpl#getCampo()
     * @generated
     */
    EClass CAMPO = eINSTANCE.getCampo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAMPO__NAME = eINSTANCE.getCampo_Name();

    /**
     * The meta object literal for the '<em><b>Nombre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAMPO__NOMBRE = eINSTANCE.getCampo_Nombre();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAMPO__TIPO = eINSTANCE.getCampo_Tipo();

    /**
     * The meta object literal for the '<em><b>Longitud</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAMPO__LONGITUD = eINSTANCE.getCampo_Longitud();

    /**
     * The meta object literal for the '{@link org.xtext.example.guioas.guiOas.impl.ValidadorImpl <em>Validador</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.guioas.guiOas.impl.ValidadorImpl
     * @see org.xtext.example.guioas.guiOas.impl.GuiOasPackageImpl#getValidador()
     * @generated
     */
    EClass VALIDADOR = eINSTANCE.getValidador();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALIDADOR__NAME = eINSTANCE.getValidador_Name();

    /**
     * The meta object literal for the '<em><b>Nombre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALIDADOR__NOMBRE = eINSTANCE.getValidador_Nombre();

    /**
     * The meta object literal for the '<em><b>Locacion</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALIDADOR__LOCACION = eINSTANCE.getValidador_Locacion();

  }

} //GuiOasPackage
