/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.guioas.guiOas;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Validador</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.guioas.guiOas.Validador#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.guioas.guiOas.Validador#getNombre <em>Nombre</em>}</li>
 *   <li>{@link org.xtext.example.guioas.guiOas.Validador#getLocacion <em>Locacion</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.guioas.guiOas.GuiOasPackage#getValidador()
 * @model
 * @generated
 */
public interface Validador extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.guioas.guiOas.GuiOasPackage#getValidador_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.guioas.guiOas.Validador#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nombre</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre</em>' attribute.
   * @see #setNombre(String)
   * @see org.xtext.example.guioas.guiOas.GuiOasPackage#getValidador_Nombre()
   * @model
   * @generated
   */
  String getNombre();

  /**
   * Sets the value of the '{@link org.xtext.example.guioas.guiOas.Validador#getNombre <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre</em>' attribute.
   * @see #getNombre()
   * @generated
   */
  void setNombre(String value);

  /**
   * Returns the value of the '<em><b>Locacion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Locacion</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Locacion</em>' attribute.
   * @see #setLocacion(String)
   * @see org.xtext.example.guioas.guiOas.GuiOasPackage#getValidador_Locacion()
   * @model
   * @generated
   */
  String getLocacion();

  /**
   * Sets the value of the '{@link org.xtext.example.guioas.guiOas.Validador#getLocacion <em>Locacion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Locacion</em>' attribute.
   * @see #getLocacion()
   * @generated
   */
  void setLocacion(String value);

} // Validador
