/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.guioas.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.guioas.ui.internal.GuioasActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GuiOasExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GuioasActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GuioasActivator.getInstance().getInjector(GuioasActivator.ORG_XTEXT_EXAMPLE_GUIOAS_GUIOAS);
	}
	
}
