/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.guioas.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.guioas.ui.AbstractGuiOasUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GuiOasUiModule extends AbstractGuiOasUiModule {
  public GuiOasUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
