/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.guioas;

import org.xtext.example.guioas.AbstractGuiOasRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GuiOasRuntimeModule extends AbstractGuiOasRuntimeModule {
}
