/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.guioas;

import org.xtext.example.guioas.GuiOasStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GuiOasStandaloneSetup extends GuiOasStandaloneSetupGenerated {
  public static void doSetup() {
    GuiOasStandaloneSetup _guiOasStandaloneSetup = new GuiOasStandaloneSetup();
    _guiOasStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
