/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.guioas.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GuiOasAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/guioas/parser/antlr/internal/InternalGuiOas.tokens");
	}
}
