/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.guioas.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.guioas.parser.antlr.internal.InternalGuiOasParser;
import org.xtext.example.guioas.services.GuiOasGrammarAccess;

public class GuiOasParser extends AbstractAntlrParser {

	@Inject
	private GuiOasGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGuiOasParser createParser(XtextTokenStream stream) {
		return new InternalGuiOasParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Entidad";
	}

	public GuiOasGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GuiOasGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
