/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.guioas.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.guioas.ui.internal.GuioasActivator;

public class GuiOasUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GuioasActivator.getInstance().getInjector("org.xtext.example.guioas.GuiOas");
	}

}
