/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.guioas.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GuiOasGrammarAccess extends AbstractGrammarElementFinder {
	
	public class EntidadElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.guioas.GuiOas.Entidad");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEntidadKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNombreAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNombreSTRINGTerminalRuleCall_1_0 = (RuleCall)cNombreAssignment_1.eContents().get(0);
		private final Keyword cCamposKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCamposAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCamposCampoParserRuleCall_4_0 = (RuleCall)cCamposAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cEntidadesKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cEntidadesAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cEntidadesEntidadParserRuleCall_8_0 = (RuleCall)cEntidadesAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Entidad:
		//	'entidad' nombre=STRING
		//	'campos' '{'
		//	campos+=Campo*
		//	'}'
		//	'entidades' '{'
		//	entidades+=Entidad*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'entidad' nombre=STRING 'campos' '{' campos+=Campo* '}' 'entidades' '{' entidades+=Entidad* '}'
		public Group getGroup() { return cGroup; }
		
		//'entidad'
		public Keyword getEntidadKeyword_0() { return cEntidadKeyword_0; }
		
		//nombre=STRING
		public Assignment getNombreAssignment_1() { return cNombreAssignment_1; }
		
		//STRING
		public RuleCall getNombreSTRINGTerminalRuleCall_1_0() { return cNombreSTRINGTerminalRuleCall_1_0; }
		
		//'campos'
		public Keyword getCamposKeyword_2() { return cCamposKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//campos+=Campo*
		public Assignment getCamposAssignment_4() { return cCamposAssignment_4; }
		
		//Campo
		public RuleCall getCamposCampoParserRuleCall_4_0() { return cCamposCampoParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
		
		//'entidades'
		public Keyword getEntidadesKeyword_6() { return cEntidadesKeyword_6; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }
		
		//entidades+=Entidad*
		public Assignment getEntidadesAssignment_8() { return cEntidadesAssignment_8; }
		
		//Entidad
		public RuleCall getEntidadesEntidadParserRuleCall_8_0() { return cEntidadesEntidadParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class CampoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.guioas.GuiOas.Campo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCampoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cNombreAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNombreSTRINGTerminalRuleCall_2_0 = (RuleCall)cNombreAssignment_2.eContents().get(0);
		private final Assignment cTipoAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTipoSTRINGTerminalRuleCall_3_0 = (RuleCall)cTipoAssignment_3.eContents().get(0);
		private final Assignment cLongitudAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLongitudINTTerminalRuleCall_4_0 = (RuleCall)cLongitudAssignment_4.eContents().get(0);
		
		//Campo:
		//	'campo' name=ID
		//	nombre=STRING
		//	tipo=STRING
		//	longitud=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'campo' name=ID nombre=STRING tipo=STRING longitud=INT
		public Group getGroup() { return cGroup; }
		
		//'campo'
		public Keyword getCampoKeyword_0() { return cCampoKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//nombre=STRING
		public Assignment getNombreAssignment_2() { return cNombreAssignment_2; }
		
		//STRING
		public RuleCall getNombreSTRINGTerminalRuleCall_2_0() { return cNombreSTRINGTerminalRuleCall_2_0; }
		
		//tipo=STRING
		public Assignment getTipoAssignment_3() { return cTipoAssignment_3; }
		
		//STRING
		public RuleCall getTipoSTRINGTerminalRuleCall_3_0() { return cTipoSTRINGTerminalRuleCall_3_0; }
		
		//longitud=INT
		public Assignment getLongitudAssignment_4() { return cLongitudAssignment_4; }
		
		//INT
		public RuleCall getLongitudINTTerminalRuleCall_4_0() { return cLongitudINTTerminalRuleCall_4_0; }
	}
	public class ValidadorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.guioas.GuiOas.Validador");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cValidadorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cNombreAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNombreSTRINGTerminalRuleCall_2_0 = (RuleCall)cNombreAssignment_2.eContents().get(0);
		private final Assignment cLocacionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLocacionURLTerminalRuleCall_3_0 = (RuleCall)cLocacionAssignment_3.eContents().get(0);
		
		//Validador:
		//	'validador' name=ID
		//	nombre=STRING
		//	locacion=URL;
		@Override public ParserRule getRule() { return rule; }
		
		//'validador' name=ID nombre=STRING locacion=URL
		public Group getGroup() { return cGroup; }
		
		//'validador'
		public Keyword getValidadorKeyword_0() { return cValidadorKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//nombre=STRING
		public Assignment getNombreAssignment_2() { return cNombreAssignment_2; }
		
		//STRING
		public RuleCall getNombreSTRINGTerminalRuleCall_2_0() { return cNombreSTRINGTerminalRuleCall_2_0; }
		
		//locacion=URL
		public Assignment getLocacionAssignment_3() { return cLocacionAssignment_3; }
		
		//URL
		public RuleCall getLocacionURLTerminalRuleCall_3_0() { return cLocacionURLTerminalRuleCall_3_0; }
	}
	
	
	private final EntidadElements pEntidad;
	private final CampoElements pCampo;
	private final ValidadorElements pValidador;
	private final TerminalRule tURL;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GuiOasGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pEntidad = new EntidadElements();
		this.pCampo = new CampoElements();
		this.pValidador = new ValidadorElements();
		this.tURL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.guioas.GuiOas.URL");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.guioas.GuiOas".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Entidad:
	//	'entidad' nombre=STRING
	//	'campos' '{'
	//	campos+=Campo*
	//	'}'
	//	'entidades' '{'
	//	entidades+=Entidad*
	//	'}';
	public EntidadElements getEntidadAccess() {
		return pEntidad;
	}
	
	public ParserRule getEntidadRule() {
		return getEntidadAccess().getRule();
	}
	
	//Campo:
	//	'campo' name=ID
	//	nombre=STRING
	//	tipo=STRING
	//	longitud=INT;
	public CampoElements getCampoAccess() {
		return pCampo;
	}
	
	public ParserRule getCampoRule() {
		return getCampoAccess().getRule();
	}
	
	//Validador:
	//	'validador' name=ID
	//	nombre=STRING
	//	locacion=URL;
	public ValidadorElements getValidadorAccess() {
		return pValidador;
	}
	
	public ParserRule getValidadorRule() {
		return getValidadorAccess().getRule();
	}
	
	//terminal URL:
	//	('http' | 'https') '://' ('a'..'z' | 'A'..'Z' | '_' | '-' | '(' | ')' | '\\' | '/' | '.' | '0'..'9')+;
	public TerminalRule getURLRule() {
		return tURL;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
