/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.guioas.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGuiOasScopeProvider extends DelegatingScopeProvider {
}
